"""add Review

Revision ID: 0954bfabec1e
Revises: 7540e49a7cf4
Create Date: 2024-07-10 22:04:47.056326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0954bfabec1e'
down_revision = '7540e49a7cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], name=op.f('fk_review_car_id_cars')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_review_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Integer(), nullable=False))
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)

    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('cost')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
        batch_op.drop_column('cost')

    op.drop_table('review')
    # ### end Alembic commands ###
